name: hearhub
description: HearHub - Discover and use hearing support tools
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.2
  flutter_lucide: ^1.8.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sound_amplifier.png
    - assets/images/hearing_test_pro.png
    - assets/images/noise_reducer.png
    - assets/images/live_transcribe_step1.png
    - assets/images/live_transcribe_step2.png
    - assets/images/live_transcribe_step3.png
